title: This is a Title
author: Michael Lam
email: michael.lam@email.com
description: > # this means to ignore newlines until "baseurl:"
  I would add an insightful description here but I don't know what this website is for and I'm just following a tutorial.

# social links
twitter_username: @ICS3U
github_username:  michael-lam8

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
